# Generated by Django 4.0.3 on 2024-10-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'signup_table',
            },
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_name', models.CharField(max_length=40)),
                ('Departure', models.CharField(max_length=40)),
                ('Destination', models.CharField(max_length=40)),
                ('Depart', models.CharField(max_length=40)),
                ('Time', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'flight_table',
            },
        ),
    ]
