# Generated by Django 4.0.3 on 2024-10-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Passenger_name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=40)),
                ('Phone_number', models.CharField(max_length=40)),
                ('Number_pass', models.CharField(max_length=40)),
                ('Seat', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'reservation_table',
            },
        ),
    ]
