# Generated by Django 4.0.3 on 2024-10-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_management', '0002_reservations'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservations',
            table='reservations_table',
        ),
    ]
