# Generated by Django 4.0.3 on 2024-10-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_management', '0004_reservation_rename_reservations_my_alter_my_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reservation',
            new_name='reserve',
        ),
        migrations.AlterModelTable(
            name='reserve',
            table='reserve_table',
        ),
    ]
