# Generated by Django 4.0.3 on 2024-10-26 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airline_management', '0005_rename_reservation_reserve_alter_reserve_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
